### ISSUE TITLE
Frame issue

### ISSUE THREAD

**Issue by Lubsey1** [csxmli2016/DFDNet#10]
I'm running through the first 3 steps of whole frames, I can see the RestoreCropFace folder and everything looks fine.

At step 4 it just dies.

###############################################################################
###############################################################################

Final Restoring 002124.jpg
^C

I've worked back through running prints and think the offending line is here as nothing gets printed after it, but does before.
    io.imsave(save_path, merge_img.astype(np.uint8))
line 76 test_FaceDict.py

I've checked file paths and they are all correct.

**Comment by Lubsey1** [comment]
Ok I've fixed it.
I was inputting 1920x1080 res images, not realising it was trying to scale them up 4x.

UpScaleWhole = 1  # the upsamle scale. It should be noted that our face results are fixed to 512.

Switching that from 4 to 1 has solved the issue.

**Comment by csxmli2016** [comment]
> Ok I've fixed it.
> I was inputting 1920x1080 res images, not realising it was trying to scale them up 4x.
> 
> UpScaleWhole = 1 # the upsamle scale. It should be noted that our face results are fixed to 512.
> 
> Switching that from 4 to 1 has solved the issue.

Yes, maybe it needs more time to save the large result.
