### ISSUE TITLE
Step 3: Error

### ISSUE THREAD

**Issue by mrsatana666** [csxmli2016/DFDNet#11]
Hello guys!

Tell me what could be wrong? How can I enable debugging?

Or does the code not work under Windows?

![image](https://user-images.githubusercontent.com/23654133/90251423-24414600-de57-11ea-836f-5eb93d9ad03a.png)

**Comment by csxmli2016** [comment]
> Hello guys!
> 
> Tell me what could be wrong? How can I enable debugging?
> 
> Or does the code not work under Windows?
> 
> ![image](https://user-images.githubusercontent.com/23654133/90251423-24414600-de57-11ea-836f-5eb93d9ad03a.png)

Hi, I add 'try' to capture the error in running the model in line 248. You can comment them to see what happened.

**Comment by csxmli2016** [comment]
> Hello guys!
> 
> Tell me what could be wrong? How can I enable debugging?
> 
> Or does the code not work under Windows?
> 
> ![image](https://user-images.githubusercontent.com/23654133/90251423-24414600-de57-11ea-836f-5eb93d9ad03a.png)

Hi, I have updated the code in line 248 by printing the exception information. You can try it again and check what is wrong with the current one.

**Comment by mrsatana666** [comment]
> > Hello guys!
> > Tell me what could be wrong? How can I enable debugging?
> > Or does the code not work under Windows?
> > ![image](https://user-images.githubusercontent.com/23654133/90251423-24414600-de57-11ea-836f-5eb93d9ad03a.png)
> 
> Hi, I have updated the code in line 248 by printing the exception information. You can try it again and check what is wrong with the current one.

Thx! Memory GPU :(

RuntimeError: CUDA out of memory. Tried to allocate 758.00 MiB (GPU 0; 4.00 GiB total capacity; 2.10 GiB already allocated; 310.67 MiB free; 2.33 GiB reserved in total by PyTorch)

**Comment by mrsatana666** [comment]
Cpu mode wrote error

Traceback (most recent call last):
  File "test_FaceDict.py", line 251, in <module>
    save_crop(visuals,os.path.join(SaveRestorePath,ImgName))
  File "C:\_remini\DFDNet-whole\util\visualizer.py", line 47, in save_crop
    im = util.tensor2im(im_data)
AttributeError: module 'util' has no attribute 'tensor2im'

Say, please, what do meane?

**Comment by csxmli2016** [comment]
> Cpu mode wrote error
> 
> Traceback (most recent call last):
> File "test_FaceDict.py", line 251, in
> save_crop(visuals,os.path.join(SaveRestorePath,ImgName))
> File "C:_remini\DFDNet-whole\util\visualizer.py", line 47, in save_crop
> im = util.tensor2im(im_data)
> AttributeError: module 'util' has no attribute 'tensor2im'
> 
> Say, please, what do meane?

Hi, it runs successfully in my computer on cpu mode. I also note that in the file ```./util/util.py```, it has the definition of ```tensor2im`. Can you debug it to check whether it can load this function?

**Comment by mrsatana666** [comment]
I solved problem =)I replaced line 5 "import util " the "from util import util"
It's work! :)

Tell me, is it possible to run the code using GPU (1050TI)?

**Comment by csxmli2016** [comment]
> I solved problem =)I replaced line 5 "import util " the "from util import util"
> It's work! :)
> 
> Tell me, is it possible to run the code using GPU (1050TI)?

Hi, I did not have 1050TI, thus I am not sure whether it can work.

**Comment by mrsatana666** [comment]
> > I solved problem =)I replaced line 5 "import util " the "from util import util"
> > It's work! :)
> > Tell me, is it possible to run the code using GPU (1050TI)?
> 
> Hi, I did not have 1050TI, thus I am not sure whether it can work.

Hi, please tell me which video card do you have?

**Comment by csxmli2016** [comment]
> > > I solved problem =)I replaced line 5 "import util " the "from util import util"
> > > It's work! :)
> > > Tell me, is it possible to run the code using GPU (1050TI)?
> > 
> > 
> > Hi, I did not have 1050TI, thus I am not sure whether it can work.
> 
> Hi, please tell me which video card do you have?

Currently, I use RTX 2080 Ti.

**Comment by mrsatana666** [comment]
> > > > I solved problem =)I replaced line 5 "import util " the "from util import util"
> > > > It's work! :)
> > > > Tell me, is it possible to run the code using GPU (1050TI)?
> > > 
> > > 
> > > Hi, I did not have 1050TI, thus I am not sure whether it can work.
> > 
> > 
> > Hi, please tell me which video card do you have?
> 
> Currently, I use RTX 2080 Ti.

Thx! And thx for your work! really looking forward to the opportunity to work with multiple faces =)

**Comment by csxmli2016** [comment]
> > > > > I solved problem =)I replaced line 5 "import util " the "from util import util"
> > > > > It's work! :)
> > > > > Tell me, is it possible to run the code using GPU (1050TI)?
> > > > 
> > > > 
> > > > Hi, I did not have 1050TI, thus I am not sure whether it can work.
> > > 
> > > 
> > > Hi, please tell me which video card do you have?
> > 
> > 
> > Currently, I use RTX 2080 Ti.
> 
> Thx! And thx for your work! really looking forward to the opportunity to work with multiple faces =)

Hi, I plan to achieve this model on multiple faces when I am free. Maybe the next several months.
