### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by test1230-lab** [csxmli2016/DFDNet#16]
Were the examples unseen data? Were they cherry picked?

**Comment by csxmli2016** [comment]
> Were the examples unseen data? Were they cherry picked?

Hi, these examples are selected from internet, which are unseen in the training phase and are real-world low-quality images. In most cases, our model can generate plausible results. There are also [some other results](https://www.youtube.com/watch?v=oQQ0M8km47k) tested by [bycloud](https://www.youtube.com/channel/UCgfe2ooZD3VJPB6aJAnuQng). Just try it.
