### ISSUE TITLE
Google Colab Notebook of your code

### ISSUE THREAD

**Issue by hopperrr** [csxmli2016/DFDNet#17]
Here is a Google Colab notebook of DFDNet I put together. Thanks for your great work.
https://github.com/hopperrr/DFDNet_Colab

**Comment by csxmli2016** [comment]
> Here is a Google Colab notebook of DFDNet I put together. Thanks for your great work.
> https://github.com/hopperrr/DFDNet_Colab

Really thanks for your tremendous help.
