### ISSUE TITLE
Loading pre-train model

### ISSUE THREAD

**Issue by currypurin** [csxmli2016/DFDNet#2]
Thanks for the great paper and for sharing the code.

Currently, the code does not seem to be able to load the pre-train model.
I modified model/network.py as follows and it generated successfully.

```
netG = UNetDictFace(64)
```
 ↓
```
netG = UNetDictFace(64)
netG.load_state_dict(torch.load('./weights/latest_net_G.pth'))
```

thank you!

**Comment by csxmli2016** [comment]
> Thanks for the great paper and for sharing the code.
> 
> Currently, the code does not seem to be able to load the pre-train model.
> I modified model/network.py as follows and it generated successfully.
> 
> ```
> netG = UNetDictFace(64)
> ```
> 
> ↓
> 
> ```
> netG = UNetDictFace(64)
> netG.load_state_dict(torch.load('./weights/latest_net_G.pth'))
> ```
> 
> thank you!

Hi, thanks for pointing out this problem. This is caused by the wrong url path. I have updated the folder structure in Readme. Please refer to it for better understanding.
