### ISSUE TITLE
Grey faces when running test image

### ISSUE THREAD

**Issue by alexschwantes** [csxmli2016/DFDNet#20]
Hi, I ran this in colab and am getting a weird output where the faces are grey and not coloured correctly.
You can check out the colab here https://colab.research.google.com/drive/1EvZeY66KeLQSTbCeRUpTciAwKJSjXa5T?usp=sharing

[![de5KR1.th.jpg](https://iili.io/de5KR1.th.jpg)](https://freeimage.host/i/de5KR1) [![de5AJI.th.jpg](https://iili.io/de5AJI.th.jpg)](https://freeimage.host/i/de5AJI)

Any idea what is going on?
Thanks.

**Comment by csxmli2016** [comment]
> Hi, I ran this in colab and am getting a weird output where the faces are grey and not coloured correctly.
> You can check out the colab here https://colab.research.google.com/drive/1EvZeY66KeLQSTbCeRUpTciAwKJSjXa5T?usp=sharing
> 
> [![de5KR1.th.jpg](https://camo.githubusercontent.com/5fbaf66f2e367fc78dc3cb68c0fd3b85f71c4bbc/68747470733a2f2f69696c692e696f2f6465354b52312e74682e6a7067)](https://freeimage.host/i/de5KR1) [![de5AJI.th.jpg](https://camo.githubusercontent.com/4fffa0b1245333148b57743943faf623cc32b4ce/68747470733a2f2f69696c692e696f2f646535414a492e74682e6a7067)](https://freeimage.host/i/de5AJI)
> 
> Any idea what is going on?
> Thanks.

Hi, I am not familiar with Colab. Maybe you can open a new issue in [hopperrr](https://github.com/hopperrr/DFDNet_Colab).

**Comment by alexschwantes** [comment]
Thanks, I didn't use the colab from hopperrr as I didn't see it before doing my own.

I found the issue, I thought I had an issue with the checkpoints directory, so I renamed it to `checkcpts` and passed the parameter `--checkpoints_dir ./chekcpts`. This is what was causing it. When I changed it back to `checkpoints`, it worked. (you just can't browse it in colab)...

Also worth noting, you missed a prerequisite for `dominate` package.

Great work btw :)

**Comment by csxmli2016** [comment]
> Thanks, I didn't use the colab from hopperrr as I didn't see it before doing my own.
> 
> I found the issue, I thought I had an issue with the checkpoints directory, so I renamed it to `checkcpts` and passed the parameter `--checkpoints_dir ./chekcpts`. This is what was causing it. When I changed it back to `checkpoints`, it worked. (you just can't browse it in colab)...
> 
> Also worth noting, you missed a prerequisite for `dominate` package.
> 
> Great work btw :)

Thanks. I will update the readme.
