### ISSUE TITLE
Just enhance the photo wihout upscaling?

### ISSUE THREAD

**Issue by ZeroCool22** [csxmli2016/DFDNet#21]
Lets say i want to just enhance the face without upscaling....

What value i should put in **UpScaleWhole =** ? Just leave it empty or put 0?

Or the enhance is only possible when upscaling?

**Comment by csxmli2016** [comment]
> Lets say i want to just enhance the face without upscaling....
> 
> What value i should put in **UpScaleWhole =** ? Just leave it empty or put 0?
> 
> Or the enhance is only possible when upscaling?

Just set UpScaleWhole = 1. you can run the following code in the command:
```
python test_FaceDict.py --test_path ./TestData/TestWhole --results_dir ./Results/TestWholeResults --upscale_factor 1 --gpu_ids 0
```

**Comment by ZeroCool22** [comment]
> 
> 
> > Lets say i want to just enhance the face without upscaling....
> > What value i should put in **UpScaleWhole =** ? Just leave it empty or put 0?
> > Or the enhance is only possible when upscaling?
> 
> Just set UpScaleWhole = 1. you can run the following code in the command:
> 
> ```
> python test_FaceDict.py --test_path ./TestData/TestWhole --results_dir ./Results/TestWholeResults --upscale_factor 1 --gpu_ids 0
> ```

Hey, thx for reply and thx for this amazing repo!

I would like to ask you something, keep in mind i'm not a expert on Machine Learning/Deep Learning.

This is the same method that the APP (for phones) **"REMINI"** use? (i know they do all the process on their servers side)

And what would be needed to enhance the **complete** photo and not just only the face?

There is a Soft that let you Enchance/Upscale whole images, it's **Topaz GigaPixel**, but it doesn't come even close to the power your repo have to enchance faces.

**Comment by csxmli2016** [comment]
> > > Lets say i want to just enhance the face without upscaling....
> > > What value i should put in **UpScaleWhole =** ? Just leave it empty or put 0?
> > > Or the enhance is only possible when upscaling?
> > 
> > 
> > Just set UpScaleWhole = 1. you can run the following code in the command:
> > ```
> > python test_FaceDict.py --test_path ./TestData/TestWhole --results_dir ./Results/TestWholeResults --upscale_factor 1 --gpu_ids 0
> > ```
> 
> Hey, thx for reply and thx for this amazing repo!
> 
> I would like to ask you something, keep in mind i'm not a expert on Machine Learning/Deep Learning.
> 
> This is the same method that the APP (for phones) **"REMINI"** use? (i know they do all the process on their servers side)
> 
> And what would be needed to enhance the **complete** photo and not just only the face?
> 
> There is a Soft that let you Enchance/Upscale whole images, it's **Topaz GigaPixel**, but it doesn't come even close to the power your repo have to enchance faces.
Hi, thanks for your interest. 
1. Our method is not used in any Apps. It is released only for research.
2. We can train a general image restoration model (not only super-resolution, or denoise), which can enhance the background. Due to the complex degradation or structures of natural image, this model can not have an obvious improvement than faces achieve. Thus, as for enhancing the complete photo, I would enhance the background with general image restoration but at the same time use our DFDNet to enhance face region. These two results are fused to generate the final complete result.  I think this may be a reasonable way to achieve this goal.

**Comment by ZeroCool22** [comment]
Thx for the explanation.

I correct myself, REMINI does improve the rest of the image too.

Here i did a comparision on upscaling a image with 3 upscaling methods/soft:

![Comparision Upsacale AI](https://user-images.githubusercontent.com/13344308/90713329-73361380-e27b-11ea-90b0-b3dfa0587fba.jpg)

I know it may not be a fair comparison for DFDNet, because it just work for the face, but if we just focus on the face, DFDNet did a great job. Better than Gigapixel, who add strange artifacts on the eyes.

PD: x2 Upscale.

**Comment by csxmli2016** [comment]
> Thx for the explanation.
> 
> I correct myself, REMINI does improve the rest of the image too.
> 
> Here i did a comparision on upscaling a image with 3 upscaling methods/soft:
> 
> ![Comparision Upsacale AI](https://user-images.githubusercontent.com/13344308/90713329-73361380-e27b-11ea-90b0-b3dfa0587fba.jpg)
> 
> I know it may not be a fair comparison for DFDNet, because it just work for the face, but if we just focus on the face, DFDNet did a great job. Better than Gigapixel, who add strange artifacts on the eyes.
> 
> PD: x2 Upscale.

Hi, thanks for your comparison. I also test the given input on face region. The enhanced face is shown below. It looks acceptable.
![face](https://user-images.githubusercontent.com/26357039/90714498-5e3c9d00-e2da-11ea-83c9-28dce196f899.png)

**Comment by ZeroCool22** [comment]
Yeah, you just gave me a great idea about combining 2 method for get the whole image:

https://vimeo.com/449536781 :D

Thx again for your great repo!

PD: You can close it if you want.

**Comment by csxmli2016** [comment]
> Yeah, you just gave me a great idea about combining 2 method for get the whole image:
> 
> https://vimeo.com/449536781 :D
> 
> Thx again for your great repo!
> 
> PD: You can close it if you want.

Yeah. This is easy to combine them in our DFDNet. Just revise the [upsample_img](https://github.com/csxmli2016/DFDNet/blob/80db1853e8789bc1227339419b7f07ece0009aff/test_FaceDict.py#L70) with the enhanced result from another general restoration model.
