### ISSUE TITLE
Training instructions.

### ISSUE THREAD

**Issue by LexTypeC** [csxmli2016/DFDNet#22]
I notice there does not seem to be any indicator as to how we'd go about training/fine tuning the net on our own datasets, this is something I (and I suspect other people) would be very interested in. I'm quite curious as to how the model would perform with say further segmentation of facial components (e.g handling eyebrows and eyes separately) as well as fine tuning models trained on general face datasets on datasets of a specific person.

With that said I'd like to request that if it is possible, the steps for training be added to the readme page :D

**Comment by csxmli2016** [comment]
> I notice there does not seem to be any indicator as to how we'd go about training/fine tuning the net on our own datasets, this is something I (and I suspect other people) would be very interested in. I'm quite curious as to how the model would perform with say further segmentation of facial components (e.g handling eyebrows and eyes separately) as well as fine tuning models trained on general face datasets on datasets of a specific person.
> 
> With that said I'd like to request that if it is possible, the steps for training be added to the readme page :D

Training details can be found in our paper. Please carefully refer to it.
