### ISSUE TITLE
error

### ISSUE THREAD

**Issue by test1230-lab** [csxmli2016/DFDNet#23]
(base) test@test-XPS-8700:~/DFDNet$ python test_FaceDict.py --test_path ./TestData/TestWhole --results_dir ./Results/TestWholeResults --upscale_factor 4 --gpu_ids 0

###############################################################################
###############################################################################

Crop and Align test1.jpg image
Crop and Align test2.jpg image
Crop and Align test3.jpg image
Crop and Align test4.jpg image
Crop and Align test5.jpg image

###############################################################################
###############################################################################

Detecting test1.jpg
Detecting test2.jpg
Detecting test3.jpg
Detecting test4.jpg
Detecting test5.jpg

###############################################################################
###############################################################################

Traceback (most recent call last):
  File "test_FaceDict.py", line 242, in <module>
    model.setup(opt)
  File "/home/test/DFDNet/models/base_model.py", line 43, in setup
    self.load_networks(opt.which_epoch)
  File "/home/test/DFDNet/models/base_model.py", line 131, in load_networks
    state_dict = torch.load(load_path, map_location=str(self.device))
  File "/home/test/.local/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/test/.local/lib/python3.7/site-packages/torch/serialization.py", line 772, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 131262 got 512

**Comment by test1230-lab** [comment]
https://pastebin.com/pQMhcPDn dir tree

**Comment by test1230-lab** [comment]
same issue in conda env

**Comment by csxmli2016** [comment]
> (base) test@test-XPS-8700:~/DFDNet$ python test_FaceDict.py --test_path ./TestData/TestWhole --results_dir ./Results/TestWholeResults --upscale_factor 4 --gpu_ids 0
> 
> ###################### Now Running the X 4 task ##############################
> 
> ###############################################################################
> ####################### Step 1: Crop and Align Face ###########################
> ###############################################################################
> 
> Crop and Align test1.jpg image
> Crop and Align test2.jpg image
> Crop and Align test3.jpg image
> Crop and Align test4.jpg image
> Crop and Align test5.jpg image
> 
> ###############################################################################
> ####################### Step 2: Face Landmark Detection #######################
> ###############################################################################
> 
> Detecting test1.jpg
> Detecting test2.jpg
> Detecting test3.jpg
> Detecting test4.jpg
> Detecting test5.jpg
> 
> ###############################################################################
> ####################### Step 3: Face Restoration ##############################
> ###############################################################################
> 
> Traceback (most recent call last):
> File "test_FaceDict.py", line 242, in
> model.setup(opt)
> File "/home/test/DFDNet/models/base_model.py", line 43, in setup
> self.load_networks(opt.which_epoch)
> File "/home/test/DFDNet/models/base_model.py", line 131, in load_networks
> state_dict = torch.load(load_path, map_location=str(self.device))
> File "/home/test/.local/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
> return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
> File "/home/test/.local/lib/python3.7/site-packages/torch/serialization.py", line 772, in _legacy_load
> deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
> RuntimeError: storage has wrong size: expected 131262 got 512

Hi, which pytorch version do you use? Maybe this is caused by the older version.

**Comment by test1230-lab** [comment]
1.16.0

**Comment by csxmli2016** [comment]
> 1.16.0

Hi, I am sorry about this issue. I do not know how to solve it. Since this situation can not be reproduced on my computer, I can not debug it. 
But I find some similar answers, that may help you.
https://discuss.pytorch.org/t/runtimeerror-storage-has-wrong-size-expected-0-got-1/41289/8

I will keep this issue open until it is solved.

**Comment by test1230-lab** [comment]
I will do some testing and let you know. I will reinstall as well

**Comment by test1230-lab** [comment]
I may try downgrading pytorch

**Comment by test1230-lab** [comment]
the file structure looks good right?

**Comment by csxmli2016** [comment]
> the file structure looks good right?

It looks right.

**Comment by test1230-lab** [comment]
###################### Now Running the X 4 task ##############################

###############################################################################
####################### Step 1: Crop and Align Face ###########################
###############################################################################

Traceback (most recent call last):
  File "_internal\DFDNet-whole\test_FaceDict.py", line 166, in <module>
    detector = dlib.cnn_face_detection_model_v1('./packages/mmod_human_face_detector.dat')
RuntimeError: Unable to open ./packages/mmod_human_face_detector.dat for reading. 



Have you seen this error?

**Comment by csxmli2016** [comment]
> ###################### Now Running the X 4 task ##############################
> 
> ###############################################################################
> ####################### Step 1: Crop and Align Face ###########################
> ###############################################################################
> 
> Traceback (most recent call last):
> File "_internal\DFDNet-whole\test_FaceDict.py", line 166, in
> detector = dlib.cnn_face_detection_model_v1('./packages/mmod_human_face_detector.dat')
> RuntimeError: Unable to open ./packages/mmod_human_face_detector.dat for reading.
> 
> Have you seen this error?

I did not meet this error. Maybe, this is caused by the wrong path url. But I observe that you have successfully run the Step 1 in https://github.com/csxmli2016/DFDNet/issues/23#issue-684963749.

**Comment by test1230-lab** [comment]
That file exists

**Comment by test1230-lab** [comment]
I'll email you mega link to folder with it installed with local python in that folder

**Comment by test1230-lab** [comment]
The last error I reported was due to a bad path, no fixing on your part needed. But i noticed that the first step is extremely slow for 1080p frames. It took about 3 mins for one frame. How can this be sped up?

**Comment by csxmli2016** [comment]
> The last error I reported was due to a bad path, no fixing on your part needed. But i noticed that the first step is extremely slow for 1080p frames. It took about 3 mins for one frame. How can this be sped up?

Maybe it mainly based on the computer configuration?
![RUJ5~K_EGT5 AN@)2N7A@85](https://user-images.githubusercontent.com/26357039/91248566-853a1980-e787-11ea-8074-a7ed094ff49e.png)
 I also test the 1080p images, and it only takes 1s on average to handle each frame.

**Comment by test1230-lab** [comment]
Any ideas for what I could have done wrong

**Comment by csxmli2016** [comment]
> Any ideas for what I could have done wrong

We run the same code, so the slow speed may be caused by different computer configurations (I use i7 cpu, 64G mem, and RTX 2080). I am also curious about the huge difference, e.g., 3min vs 1s.

**Comment by test1230-lab** [comment]
https://mega.nz/file/YYZwmISQ#NpxOTvKUfcKlJIMnEX3AevjDGjhCR3cVUBWgd5HFI5k has python install and dfdnet and bat file

**Comment by test1230-lab** [comment]
Is the link working?

**Comment by csxmli2016** [comment]
> Is the link working?

Sorry, I can not download this file.

**Comment by test1230-lab** [comment]
What's this issue

**Comment by test1230-lab** [comment]
Is there a site that works for you?

**Comment by csxmli2016** [comment]
> Is there a site that works for you?

How about google drive?

**Comment by test1230-lab** [comment]
ill have the link in 30mins

**Comment by test1230-lab** [comment]
https://drive.google.com/file/d/1Gpm9P8oG8tqLdf1pm1WXhC9Rrt0uYRLl/view?usp=sharing

**Comment by test1230-lab** [comment]
make sure to run with the bat files so it uses the python that came with the folder

**Comment by csxmli2016** [comment]
> make sure to run with the bat files so it uses the python that came with the folder

Hi, my server is ubuntu, so I can not run your code directly.

**Comment by test1230-lab** [comment]
oh ok

**Comment by test1230-lab** [comment]
ill make .sh file tommorow

**Comment by test1230-lab** [comment]
Could you edit the bat files to be sh files? I won't have access to my pc for a couple days. Or will it not work due to python?

**Comment by brunodbrazil** [comment]
Friends, I have the same problem in step 1. It takes about 1 minute for each image at 970x720. My computer uses a 2080ti, 64gb. Why is it so slow?

**Comment by csxmli2016** [comment]
> Friends, I have the same problem in step 1. It takes about 1 minute for each image at 970x720. My computer uses a 2080ti, 64gb. Why is it so slow?

Can you debug it to find which code cost so many times? 
dlib.load_rgb_image, tform.estimate or others?

**Comment by brunodbrazil** [comment]
> > Amigos, tenho o mesmo problema na etapa 1. Demora cerca de 1 minuto para cada imagem em 970x720. Meu computador usa um 2080ti, 64gb. Por que é tão lento?
> 
> Você pode depurá-lo para descobrir qual código custa tantas vezes?
> dlib.load_rgb_image, tform.estimate ou outros?

I do not know how to do this. Could you instruct me?

**Comment by csxmli2016** [comment]
> > > Amigos, tenho o mesmo problema na etapa 1. Demora cerca de 1 minuto para cada imagem em 970x720. Meu computador usa um 2080ti, 64gb. Por que é tão lento?
> > 
> > 
> > Você pode depurá-lo para descobrir qual código custa tantas vezes?
> > dlib.load_rgb_image, tform.estimate ou outros?
> 
> I do not know how to do this. Could you instruct me?

Just use time package to compute the time, e.g.:
```
import time
st1 = time.time()
dlib.load_rgb_image
et1 = time.time()
print(et1-st1)
```

**Comment by test1230-lab** [comment]
If you like you could remote into my windows machine to debug.

**Comment by brunodbrazil** [comment]
> asta usar o pacote de tempo para calcular o tempo, p



> > > > Amigos, tenho o mesmo problema na etapa 1. Demora cerca de 1 minuto para cada imagem em 970x720. Meu computador usa um 2080ti, 64gb. Por que é tão lento?
> > > 
> > > 
> > > Você pode depurá-lo para descobrir qual código custa tantas vezes?
> > > dlib.load_rgb_image, tform.estimate ou outros?
> > 
> > 
> > I do not know how to do this. Could you instruct me?
> 
> Just use time package to compute the time, e.g.:
> 
> ```
> import time
> st1 = time.time()
> dlib.load_rgb_image
> et1 = time.time()
> print(et1-st1)
> ```


I really don't know how to do that. If you also want to access my machine remotely, I can allow it.

**Comment by csxmli2016** [comment]
> > asta usar o pacote de tempo para calcular o tempo, p
> 
> > > > > Amigos, tenho o mesmo problema na etapa 1. Demora cerca de 1 minuto para cada imagem em 970x720. Meu computador usa um 2080ti, 64gb. Por que é tão lento?
> > > > 
> > > > 
> > > > Você pode depurá-lo para descobrir qual código custa tantas vezes?
> > > > dlib.load_rgb_image, tform.estimate ou outros?
> > > 
> > > 
> > > I do not know how to do this. Could you instruct me?
> > 
> > 
> > Just use time package to compute the time, e.g.:
> > ```
> > import time
> > st1 = time.time()
> > dlib.load_rgb_image
> > et1 = time.time()
> > print(et1-st1)
> > ```
> 
> I really don't know how to do that. If you also want to access my machine remotely, I can allow it.

Hi, @test1230-lab  @brunodbrazil, I will use another windows server to check the running situation within this week.

**Comment by test1230-lab** [comment]
ok no rush

**Comment by brunodbrazil** [comment]
> l use another windows server to check the running situation within this week.

thanks, bro

**Comment by joedit-cmd** [comment]
@brunodbrazil is DFDNet loaded on a physical spinning hard drive, or on SSD/NVMe? I had similar issue and it was very slow on spinning hard drive. It runs much faster on ssd.

**Comment by test1230-lab** [comment]
i was on hdd

**Comment by brunodbrazil** [comment]
> @brunodbrazil is DFDNet loaded on a physical spinning hard drive, or on SSD/NVMe? I had similar issue and it was very slow on spinning hard drive. It runs much faster on ssd.

i was on hdd. I will test a SSD now. Thanks!

**Comment by brunodbrazil** [comment]
> @brunodbrazil é DFDNet carregado em um disco rígido giratório físico ou em SSD / NVMe? Eu tive um problema semelhante e era muito lento na rotação do disco rígido. Ele roda muito mais rápido em ssd.

Don't work. Still slow. I tryed use a SSD M.2

**Comment by csxmli2016** [comment]
@test1230-lab @brunodbrazil  I test the codes in windows server on hdd. It still runs normally. I think it is mainly caused by the dlib. Maybe you can reinstall the dlib by python setup.py install from its original codes. Also, you should make sure that there is only one dlib version. Since I meet the situation that the DFDNet used the conda env dlib rather than the one I builded from dlib codes. Just run conda uninstall dlib and install dlib from the official github code. Besides this, I could not find other reasons.

**Comment by test1230-lab** [comment]
what conda/pip commands were used to install dlib?

**Comment by csxmli2016** [comment]
> what conda/pip commands were used to install dlib?

Maybe you can refer to the [original codes ](https://github.com/davisking/dlib).  Maybe it will use cuda support.
