### ISSUE TITLE
Error in enhancing this image

### ISSUE THREAD

**Issue by Ricelll** [csxmli2016/DFDNet#25]
Hi, Excuse me, 
when I just Run the **Face_Restoration** function with aligned image(512*512), it occured to a question :
"################ Error in enhancing this image: input and output sizes should be greater than 0, but got input (H: 16, W: 0) output (H: 40, W: 40)"
I checked the class UNetDictFace in network.py carefully,  i find:
cur_feature is the shape of [1, 128, 256, 256];
mo_location  is the shape of [4],and its value is [205, 288, 242, 325];
then ;
MO_feature = cur_feature[:,:,mo_location[1]:mo_location[3],mo_location[0]:mo_location[2]].clone();
it didn't work that the value would cross the border of cur_feature.

some pics work, but some pics didn't work.
Could u tell me the reason?
thx very much!!

**Comment by csxmli2016** [comment]
> Hi, Excuse me,
> when I just Run the **Face_Restoration** function with aligned image(512*512), it occured to a question :
> "################ Error in enhancing this image: input and output sizes should be greater than 0, but got input (H: 16, W: 0) output (H: 40, W: 40)"
> I checked the class UNetDictFace in network.py carefully, i find:
> cur_feature is the shape of [1, 128, 256, 256];
> mo_location is the shape of [4],and its value is [205, 288, 242, 325];
> then ;
> MO_feature = cur_feature[:,:,mo_location[1]:mo_location[3],mo_location[0]:mo_location[2]].clone();
> it didn't work that the value would cross the border of cur_feature.
> 
> some pics work, but some pics didn't work.
> Could u tell me the reason?
> thx very much!!

Can you send me the pics that did not work? I think I should debug it to find the reason.

**Comment by Ricelll** [comment]
> > Hi, Excuse me,
> > when I just Run the **Face_Restoration** function with aligned image(512*512), it occured to a question :
> > "################ Error in enhancing this image: input and output sizes should be greater than 0, but got input (H: 16, W: 0) output (H: 40, W: 40)"
> > I checked the class UNetDictFace in network.py carefully, i find:
> > cur_feature is the shape of [1, 128, 256, 256];
> > mo_location is the shape of [4],and its value is [205, 288, 242, 325];
> > then ;
> > MO_feature = cur_feature[:,:,mo_location[1]:mo_location[3],mo_location[0]:mo_location[2]].clone();
> > it didn't work that the value would cross the border of cur_feature.
> > some pics work, but some pics didn't work.
> > Could u tell me the reason?
> > thx very much!!
> 
> Can you send me the pics that did not work? I think I should debug it to find the reason.

emm..sorry, I find my pics are not aligned.
I put the pic(the size is (102, 112, 3)) and the landmark to Face_Restoration function, it works.results are as follows.
![zhu_tuhaojin_1596692300695](https://user-images.githubusercontent.com/31204531/91273422-d0682280-e7af-11ea-8373-8fe918b7232d.jpg)
------>
![zhu_tuhaojin_1_1596692300695](https://user-images.githubusercontent.com/31204531/91273447-d958f400-e7af-11ea-91bd-b13478ebe8f7.jpg)
But the same pic(resize it to (2693, 4096, 3)) didn't work.
![zhu_tuhaojin_ff](https://user-images.githubusercontent.com/31204531/91274848-e24ac500-e7b1-11ea-8994-2883c992a633.jpg)

**Comment by csxmli2016** [comment]
> > > Hi, Excuse me,
> > > when I just Run the **Face_Restoration** function with aligned image(512*512), it occured to a question :
> > > "################ Error in enhancing this image: input and output sizes should be greater than 0, but got input (H: 16, W: 0) output (H: 40, W: 40)"
> > > I checked the class UNetDictFace in network.py carefully, i find:
> > > cur_feature is the shape of [1, 128, 256, 256];
> > > mo_location is the shape of [4],and its value is [205, 288, 242, 325];
> > > then ;
> > > MO_feature = cur_feature[:,:,mo_location[1]:mo_location[3],mo_location[0]:mo_location[2]].clone();
> > > it didn't work that the value would cross the border of cur_feature.
> > > some pics work, but some pics didn't work.
> > > Could u tell me the reason?
> > > thx very much!!
> > 
> > 
> > Can you send me the pics that did not work? I think I should debug it to find the reason.
> 
> emm..sorry, I find my pics are not aligned.
> I put the pic(the size is (102, 112, 3)) and the landmark to Face_Restoration function, it works.results are as follows.
> ![zhu_tuhaojin_1596692300695](https://user-images.githubusercontent.com/31204531/91273422-d0682280-e7af-11ea-8373-8fe918b7232d.jpg)
> ------>
> ![zhu_tuhaojin_1_1596692300695](https://user-images.githubusercontent.com/31204531/91273447-d958f400-e7af-11ea-91bd-b13478ebe8f7.jpg)
> But the same pic(resize it to (2693, 4096, 3)) didn't work.
> ![zhu_tuhaojin_ff](https://user-images.githubusercontent.com/31204531/91274848-e24ac500-e7b1-11ea-8994-2883c992a633.jpg)

Very strange. Both images ( (102, 112, 3), (2693, 4096, 3)) work well in my computer. Do you use our new code? Or did you change our code (except these four parameters in command)? With the released code, I didn't reproduce your problem.

**Comment by Ricelll** [comment]
> > > > Hi, Excuse me,
> > > > when I just Run the **Face_Restoration** function with aligned image(512*512), it occured to a question :
> > > > "################ Error in enhancing this image: input and output sizes should be greater than 0, but got input (H: 16, W: 0) output (H: 40, W: 40)"
> > > > I checked the class UNetDictFace in network.py carefully, i find:
> > > > cur_feature is the shape of [1, 128, 256, 256];
> > > > mo_location is the shape of [4],and its value is [205, 288, 242, 325];
> > > > then ;
> > > > MO_feature = cur_feature[:,:,mo_location[1]:mo_location[3],mo_location[0]:mo_location[2]].clone();
> > > > it didn't work that the value would cross the border of cur_feature.
> > > > some pics work, but some pics didn't work.
> > > > Could u tell me the reason?
> > > > thx very much!!
> > > 
> > > 
> > > Can you send me the pics that did not work? I think I should debug it to find the reason.
> > 
> > 
> > emm..sorry, I find my pics are not aligned.
> > I put the pic(the size is (102, 112, 3)) and the landmark to Face_Restoration function, it works.results are as follows.
> > ![zhu_tuhaojin_1596692300695](https://user-images.githubusercontent.com/31204531/91273422-d0682280-e7af-11ea-8373-8fe918b7232d.jpg)
> > ------>
> > ![zhu_tuhaojin_1_1596692300695](https://user-images.githubusercontent.com/31204531/91273447-d958f400-e7af-11ea-91bd-b13478ebe8f7.jpg)
> > But the same pic(resize it to (2693, 4096, 3)) didn't work.
> > ![zhu_tuhaojin_ff](https://user-images.githubusercontent.com/31204531/91274848-e24ac500-e7b1-11ea-8994-2883c992a633.jpg)
> 
> Very strange. Both images ( (102, 112, 3), (2693, 4096, 3)) work well in my computer. Do you use our new code? Or did you change our code (except these four parameters in command)? With the released code, I didn't reproduce your problem.

thank u very much.
I will check my code and try ur new code.
Thanks again.

**Comment by csxmli2016** [comment]
> > > > Hi, Excuse me,
> > > > when I just Run the **Face_Restoration** function with aligned image(512*512), it occured to a question :
> > > > "################ Error in enhancing this image: input and output sizes should be greater than 0, but got input (H: 16, W: 0) output (H: 40, W: 40)"
> > > > I checked the class UNetDictFace in network.py carefully, i find:
> > > > cur_feature is the shape of [1, 128, 256, 256];
> > > > mo_location is the shape of [4],and its value is [205, 288, 242, 325];
> > > > then ;
> > > > MO_feature = cur_feature[:,:,mo_location[1]:mo_location[3],mo_location[0]:mo_location[2]].clone();
> > > > it didn't work that the value would cross the border of cur_feature.
> > > > some pics work, but some pics didn't work.
> > > > Could u tell me the reason?
> > > > thx very much!!
> > > 
> > > 
> > > Can you send me the pics that did not work? I think I should debug it to find the reason.
> > 
> > 
> > emm..sorry, I find my pics are not aligned.
> > I put the pic(the size is (102, 112, 3)) and the landmark to Face_Restoration function, it works.results are as follows.
> > ![zhu_tuhaojin_1596692300695](https://user-images.githubusercontent.com/31204531/91273422-d0682280-e7af-11ea-8373-8fe918b7232d.jpg)
> > ------>
> > ![zhu_tuhaojin_1_1596692300695](https://user-images.githubusercontent.com/31204531/91273447-d958f400-e7af-11ea-91bd-b13478ebe8f7.jpg)
> > But the same pic(resize it to (2693, 4096, 3)) didn't work.
> > ![zhu_tuhaojin_ff](https://user-images.githubusercontent.com/31204531/91274848-e24ac500-e7b1-11ea-8994-2883c992a633.jpg)
> 
> Very strange. Both images ( (102, 112, 3), (2693, 4096, 3)) work well in my computer. Do you use our new code?



> > > > > Hi, Excuse me,
> > > > > when I just Run the **Face_Restoration** function with aligned image(512*512), it occured to a question :
> > > > > "################ Error in enhancing this image: input and output sizes should be greater than 0, but got input (H: 16, W: 0) output (H: 40, W: 40)"
> > > > > I checked the class UNetDictFace in network.py carefully, i find:
> > > > > cur_feature is the shape of [1, 128, 256, 256];
> > > > > mo_location is the shape of [4],and its value is [205, 288, 242, 325];
> > > > > then ;
> > > > > MO_feature = cur_feature[:,:,mo_location[1]:mo_location[3],mo_location[0]:mo_location[2]].clone();
> > > > > it didn't work that the value would cross the border of cur_feature.
> > > > > some pics work, but some pics didn't work.
> > > > > Could u tell me the reason?
> > > > > thx very much!!
> > > > 
> > > > 
> > > > Can you send me the pics that did not work? I think I should debug it to find the reason.
> > > 
> > > 
> > > emm..sorry, I find my pics are not aligned.
> > 
> > Very strange. Both images ( (102, 112, 3), (2693, 4096, 3)) work well in my computer. Do you use our new code? Or did you change our code (except these four parameters in command)? With the released code, I didn't reproduce your problem.
> 
> thank u very much.
> I will check my code and try ur new code.
> Thanks again.

This is the result that takes the input with 2693*4096.

![err2d](https://user-images.githubusercontent.com/26357039/91277194-14a9f180-e7b5-11ea-9dc7-8826945aaf13.jpg)
