### ISSUE TITLE
Proper way to update?

### ISSUE THREAD

**Issue by ZeroCool22** [csxmli2016/DFDNet#26]
Just download the update zip files, extract and replace?

Or should be done in another way?

Thx in advance!

**Comment by AutomatykaJava** [comment]
> Just download the update zip files, extract and replace?
> 
> Or should be done in another way?
> 
> Thx in advance!

Hi, there is video tutorial in Readme.md that will answer your question and lead you step by step. Best regards.
Replacing files would do the thing.

**Comment by csxmli2016** [comment]
> Just download the update zip files, extract and replace?
> 
> Or should be done in another way?
> 
> Thx in advance!

Just replace them.

**Comment by ZeroCool22** [comment]
> 
> 
> > Just download the update zip files, extract and replace?
> > Or should be done in another way?
> > Thx in advance!
> 
> Just replace them.

Thx.
