### ISSUE TITLE
Producing werid result 

### ISSUE THREAD

**Issue by Niellai** [csxmli2016/DFDNet#27]
Hi Sir
I try to clone your work and loaded the model provided but when i try the test script (test_FaceDict.py), it produce some weird result. Could you provide some guidance on how to correct this?

I am running the project from pop os 20.04

The follow are my python packages
python                    3.7.7 
pytorch                   1.6.0 (py3.7_cuda10.1.243_cudnn7.6.3_0)
dlib                         19.20.99
dominate                 2.4.0
opencv-python        4.2.0.34
scikit-image              0.17.2
face_alignment       1.1.0

The model I downloaded are from Google Drive.
https://drive.google.com/drive/folders/1bayYIUMCSGmoFPyd4Uu2Uwn347RW-vl5?usp=sharing

The following are the result I gotten.
![test2](https://user-images.githubusercontent.com/9927452/91259704-96901f80-e7a1-11ea-8e1a-c54dc5047243.jpg)
 
![test3](https://user-images.githubusercontent.com/9927452/91259707-97c14c80-e7a1-11ea-8e18-a2ce06212f4f.jpg)

Thanks.

**Comment by csxmli2016** [comment]
> Hi Sir
> I try to clone your work and loaded the model provided but when i try the test script (test_FaceDict.py), it produce some weird result. Could you provide some guidance on how to correct this?
> 
> I am running the project from pop os 20.04
> 
> The follow are my python packages
> python 3.7.7
> pytorch 1.6.0 (py3.7_cuda10.1.243_cudnn7.6.3_0)
> dlib 19.20.99
> dominate 2.4.0
> opencv-python 4.2.0.34
> scikit-image 0.17.2
> face_alignment 1.1.0
> 
> The model I downloaded are from Google Drive.
> https://drive.google.com/drive/folders/1bayYIUMCSGmoFPyd4Uu2Uwn347RW-vl5?usp=sharing
> 
> The following are the result I gotten.
> ![test2](https://user-images.githubusercontent.com/9927452/91259704-96901f80-e7a1-11ea-8e1a-c54dc5047243.jpg)
> 
> ![test3](https://user-images.githubusercontent.com/9927452/91259707-97c14c80-e7a1-11ea-8e18-a2ce06212f4f.jpg)
> 
> Thanks.

Very similar to https://github.com/csxmli2016/DFDNet/issues/20. Please check the checkpoints path and make sure that all the steps are followed by our instruction.

**Comment by Niellai** [comment]
Thanks I found my mistake, the directory have to be as follows. I miss out the folder in the middle.
checkpoints > **facefh_dictionary** > latest_net_G.pth

Awesome project btw, thanks for sharing.
