### ISSUE TITLE
Erorr

### ISSUE THREAD

**Issue by HamidrezaJazebi** [csxmli2016/DFDNet#28]
what's the problem here?

Crop and Align Dx8jGPoU0AAXapa.jpg image
Traceback (most recent call last):
  File "test_FaceDict.py", line 187, in <module>
    align_and_save(ImgPath, SavePath, SaveInput, SaveParam, UpScaleWhole)
  File "test_FaceDict.py", line 44, in align_and_save
    img = dlib.load_rgb_image(img_path)
AttributeError: module 'dlib' has no attribute 'load_rgb_image'

**Comment by csxmli2016** [comment]
> module 'dlib' has no attribute 'load_rgb_image'

Maybe you are using an older version of dlib. I am using dlib with 19.19. You can kindly refer to https://github.com/davisking/dlib/issues/1312#issuecomment-389826725
