### ISSUE TITLE
Cpu and gpu 

### ISSUE THREAD

**Issue by headphone0jack** [csxmli2016/DFDNet#29]
Why my cpu and gpu process  time is the same?

**Comment by csxmli2016** [comment]
> Why my cpu and gpu process time is the same?

Very strange. With these default parameters, it takes 35s and 12.8s on cpu and gpu mode, respectively. 

On cpu:
```
python test_FaceDict.py --gpu_ids -1
output: 35s
```
On gpu:
``` 
python test_FaceDict.py --gpu_ids 0
output: 12.8s
```

**Comment by alessiapacca** [comment]
hey @csxmli2016 , is this an accurate result on the timing? Can we say that the CPU runtime is almost 3 times the GPU ones? Because I don't have a suitable GPU to run the evaluation, but I would like to have precise a timing analysis
