### ISSUE TITLE
RuntimeError: Error while calling cudaOccupancyMaxPotentialBlockSize(&num_blocks,&num_threads,K)

### ISSUE THREAD

**Issue by justinjohn0306** [csxmli2016/DFDNet#30]
RuntimeError: Error while calling cudaOccupancyMaxPotentialBlockSize(&num_blocks,&num_threads,K)
shows up 

![Capture](https://user-images.githubusercontent.com/34035011/91798304-3afedf80-ec42-11ea-9131-2af8df6d6d24.PNG)

**Comment by csxmli2016** [comment]
> RuntimeError: Error while calling cudaOccupancyMaxPotentialBlockSize(&num_blocks,&num_threads,K)
> shows up
> 
> ![Capture](https://user-images.githubusercontent.com/34035011/91798304-3afedf80-ec42-11ea-9131-2af8df6d6d24.PNG)

I am not sure about this problem. But it shows that the environment about cuda, pytorch has something wrong.
