### ISSUE TITLE
how to update face dictionary

### ISSUE THREAD

**Issue by EKINGcoolbreeze** [csxmli2016/DFDNet#31]
I want to use my picture to train my eyes model dictionary in the folder DictionaryCenter512

**Comment by csxmli2016** [comment]
> I want to use my picture to train my eyes model dictionary in the folder DictionaryCenter512

Firstly, extract your picture using Vgg model. Then crop and resize them by RoIAlign. Finally, directly concat these features, which is the final DictionaryCenter512.  In this manner, it is not necessary to use Kmeans to generate the K cluster. Only concat the features to generate the dictionary.

**Comment by alessiapacca** [comment]
Once that I have generated my own dictionary, should I retrain the net?
