### ISSUE TITLE
Temporal Coherence?

### ISSUE THREAD

**Issue by test1230-lab** [csxmli2016/DFDNet#32]
How could DFDNet be changed to allow temporal coherence? https://streamable.com/wwmvuk

**Comment by csxmli2016** [comment]
> How could DFDNet be changed to allow temporal coherence? https://streamable.com/wwmvuk

This task is Video Temporal Consistency. You can refer to [Learning Blind Video Temporal Consistency](https://openaccess.thecvf.com/content_ECCV_2018/papers/Wei-Sheng_Lai_Real-Time_Blind_Video_ECCV_2018_paper.pdf).
You can incorporate our DFDNet in any methods that consider the temporal consistency.
