### ISSUE TITLE
Train 

### ISSUE THREAD

**Issue by quqxui** [csxmli2016/DFDNet#33]
Hi,  thank you very much for your open source projiect. I found it have wonderful performance in many test image. But also i found the algorithm does not pay too much attention to the details, resulting in partial animation and painting style.

 I really hope to reproduce the training process, so can you tell me more about the image processing and its related code？ 

Looking forward to your reply!

**Comment by csxmli2016** [comment]
> Hi, thank you very much for your open source projiect. I found it have wonderful performance in many test image. But also i found the algorithm does not pay too much attention to the details, resulting in partial animation and painting style.
> 
> I really hope to reproduce the training process, so can you tell me more about the image processing and its related code？
> 
> Looking forward to your reply!

Hi,
Thanks for your attention. I am also trying to improve the performance. As for other details or codes, we do not plan to release it currently.
Thanks.
