### ISSUE TITLE
some details of datasets degrade

### ISSUE THREAD

**Issue by xiaohaipeng** [csxmli2016/DFDNet#35]
1.what is the size of your gaussianblur kernel ?
2.can you provide blur kernels used in your experiment or relative codes?
3.why down-sampler r is not integer but decimal?for get images of any size? 
and the most important question is : your job is of good generalization to real LQ images,what is the most key element?model structure ? use of  face features dicts?

**Comment by csxmli2016** [comment]
> 1.what is the size of your gaussianblur kernel ?
> 2.can you provide blur kernels used in your experiment or relative codes?
> 3.why down-sampler r is not integer but decimal?for get images of any size?
> and the most important question is : your job is of good generalization to real LQ images,what is the most key element?model structure ? use of face features dicts?

1. The kernel size is randomly selected from {1:2:21}.
2. The blur kernel contains two parts, gaussian blur and motion blur. As for the later one, you can find them from the following works:
[1] Modeling the performance of image restoration from motion blur
[2] Understanding and evaluating blind deconvolution algorithms
3. Yes. Real-world images usually have different sizes.
4. The structure is a common combination of UNet and SFTGAN. It seems to have little benefits to generalize the real-world LQ image. Face dictionary has already high-quality features, which are very important in handling the random degraded images.

**Comment by xiaohaipeng** [comment]
i find SFT structure is very similar to SPADE structure, the difference is SPADE does normalization before affine . What is your consideration about the two structure?

**Comment by csxmli2016** [comment]
> i find SFT structure is very similar to SPADE structure, the difference is SPADE does normalization before affine . What is your consideration about the two structure?

Nearly the same. I did not compare them in our experiments. Both of them are very effective in their corresponding tasks.

**Comment by xiaohaipeng** [comment]
did you use all training data of VGGFace2 to train DFDNet?i found images in VGGFace2 are less clear than FFHQ, if training with the other 60000 images in FFHQ, is it able to get better performance?

**Comment by csxmli2016** [comment]
> did you use all training data of VGGFace2 to train DFDNet?i found images in VGGFace2 are less clear than FFHQ, if training with the other 60000 images in FFHQ, is it able to get better performance?

Hi, the released model is trained on FFHQ. VggFace2 is not included here due to the low resolution.

**Comment by test1230-lab** [comment]
The dataset size was only 10k correct?

**Comment by csxmli2016** [comment]
> The dataset size was only 10k correct?

Hi, the released model is somewhat different from our paper, which focused on different resolutions (256 vs 512). 10K images from FFHQ are used to conduct our dictionaries, and the released model is trained on the remaining 60,000 images.
