### ISSUE TITLE
About ROIAlign

### ISSUE THREAD

**Issue by xjw00654** [csxmli2016/DFDNet#36]
First appreciate your great works. I have simply checked the code in this repository and found a question on the component feature extraction and insertion.

I find you mentioned that using the ROIAlign for getting patches from feature maps in paper, but the code seems to simply crop patches using specified coordinates from the landmarks.

Is that a unsupported feature in this version of code 😃 .

**Comment by csxmli2016** [comment]
> First appreciate your great works. I have simply checked the code in this repository and found a question on the component feature extraction and insertion.
> 
> I find you mentioned that using the ROIAlign for getting patches from feature maps in paper, but the code seems to simply crop patches using specified coordinates from the landmarks.
> 
> Is that a unsupported feature in this version of code 😃 .

Hi, RoIAlign contains crop and resize operation. Directly Using RoIAlign is ok and faster than our code, I also test it in the later version. However, considering the reverse RoIAlign, which can not have packages to support it, I use simple crop and resize in our code.

**Comment by xjw00654** [comment]
@csxmli2016 
Thanks for your reply, I am also interested in the implementation of the reverse ROIAlign, could you simply introduce how to do it?

**Comment by csxmli2016** [comment]
> @csxmli2016
> Thanks for your reply, I am also interested in the implementation of the reverse ROIAlign, could you simply introduce how to do it?

For example, we crop the left eye and resize it from H*W to H'*W'. After enhancement, we resize the left eye from H'*W' to H*W (this is reverse RoIAlign). Then take the H*W feature to its original location.
