### ISSUE TITLE
About side view of face

### ISSUE THREAD

**Issue by Michaelwhite34** [csxmli2016/DFDNet#37]
I use a side view of face and it says "No face is detected".Is the repo designed for almost front face or I just pick a bad image.
Is it possible to deal with videos in the future ? I think it's super useful to repair highly compressed video face.

**Comment by csxmli2016** [comment]
> I use a side view of face and it says "No face is detected".Is the repo designed for almost front face or I just pick a bad image.
> Is it possible to deal with videos in the future ? I think it's super useful to repair highly compressed video face.

Hi, our DFDNet needs crop and align the face images by using dlib package. So if the face can not be detected by dlib, our DFDNet would not handle this image. But for these types of image, you can crop them manually, and then run the following steps, i.e., landmark detection, restoration. Also you can use another better package to detect face.

As for dealing with videos, it would be better to consider the consistency between frames. If possible, I will achieve this function in the future.
