### ISSUE TITLE
dfdnet-attachment

### ISSUE THREAD

**Issue by idanka** [csxmli2016/DFDNet#38]
Pls use Google Drive mirror
I upload one map to zip

https://drive.google.com/file/d/1fPze7JAJUHVUYJspRXcEQGkiMc7Vvv8-/view?usp=sharing

**Comment by csxmli2016** [comment]
Thanks very much.

**Comment by csxmli2016** [comment]
> Pls use Google Drive mirror
> I upload one map to zip
> 
> https://drive.google.com/file/d/1fPze7JAJUHVUYJspRXcEQGkiMc7Vvv8-/view?usp=sharing

Thanks very much.
