### ISSUE TITLE
Error in enhancing this image: CUDA out of memory.

### ISSUE THREAD

**Issue by idanka** [csxmli2016/DFDNet#39]
Hi!
Step 3
Restoring test1.jpg
	################ Error in enhancing this image: CUDA out of memory. Tried to allocate 758.00 MiB (GPU 0; 3.81 GiB total capacity; 2.10 GiB already allocated; 46.31 MiB free; 2.33 GiB reserved in total by PyTorch)
	################ continue...
Step 4
error
missing image, Step4_FinalResults map empty

Im use **Ubuntu 20.04**
**GeForce GTX 1650** / 4GB
Ubuntu default install: **cuda 10.1** and **libcudnn8_8.0.4.30**-1+cuda10.1_amd64

![2020-10-03 01-20-10](https://user-images.githubusercontent.com/3587195/94976898-bdffa800-0516-11eb-896c-008f50e387a4.png)

**Comment by csxmli2016** [comment]
> Hi!
> Step 3
> Restoring test1.jpg
> ################ Error in enhancing this image: CUDA out of memory. Tried to allocate 758.00 MiB (GPU 0; 3.81 GiB total capacity; 2.10 GiB already allocated; 46.31 MiB free; 2.33 GiB reserved in total by PyTorch)
> ################ continue...
> Step 4
> error
> missing image, Step4_FinalResults map empty
> 
> Im use **Ubuntu 20.04**
> **GeForce GTX 1650** / 4GB
> Ubuntu default install: **cuda 10.1** and **libcudnn8_8.0.4.30**-1+cuda10.1_amd64
> 
> ![2020-10-03 01-20-10](https://user-images.githubusercontent.com/3587195/94976898-bdffa800-0516-11eb-896c-008f50e387a4.png)

Hi, this is caused by the limited cuda memory. You can use cpu instead of gpu. 
Besides, you can also use the colab (pls refer to https://github.com/csxmli2016/DFDNet/issues/17#issue-680671802)

**Comment by alessiapacca** [comment]
I have a GEFORCE RTX 2070, how is it possible that I get the error CUDA out of memory? Which GPUs are supported?

**Comment by ivellios1988** [comment]
Exactly same problem here. My GPU is Nvidia GeForce 940MX, system is Windows 10 x64

**Comment by mowshon** [comment]
@csxmli2016 what kind of RTX do you have?
I have RTX 2070 Super 8GB and I got this error:
```
Error in enhancing this image: CUDA out of memory. Tried to allocate 758.00 MiB
(GPU 0; 7.79 GiB total capacity; 5.26 GiB already allocated;
483.88 MiB free; 5.73 GiB reserved in total by PyTorch)
```
