### ISSUE TITLE
ValueError: Could not find a format to read the specified file in single-image mode

### ISSUE THREAD

**Issue by cloudweather** [csxmli2016/DFDNet#4]
Hi,
I am trying to run `python get_face_landmark.py` with 2 test images n000024_0042_02 and n000056_0060_01
but it returned with:
```
(DFD) G:\DFDNet\DFDNet\FaceLandmarkDetection>python get_face_landmark.py
(0, 'Landmarks')
Traceback (most recent call last):
  File "get_face_landmark.py", line 28, in <module>
    imgs = io.imread(os.path.join(FilePath,name))
  File "E:\Anaconda3\envs\DFD\lib\site-packages\skimage\io\_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "E:\Anaconda3\envs\DFD\lib\site-packages\skimage\io\manage_plugins.py", line 209, in call_plugin
    return func(*args, **kwargs)
  File "E:\Anaconda3\envs\DFD\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "E:\Anaconda3\envs\DFD\lib\site-packages\imageio\core\functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "E:\Anaconda3\envs\DFD\lib\site-packages\imageio\core\functions.py", line 182, in get_reader
    "Could not find a format to read the specified file in %s mode" % modename
ValueError: Could not find a format to read the specified file in single-image mode
```
How can I get past this error?
Thanks in advance

**Comment by csxmli2016** [comment]
> Hi,
> I am trying to run `python get_face_landmark.py` with 2 test images n000024_0042_02 and n000056_0060_01
> but it returned with:
> 
> ```
> (DFD) G:\DFDNet\DFDNet\FaceLandmarkDetection>python get_face_landmark.py
> (0, 'Landmarks')
> Traceback (most recent call last):
>   File "get_face_landmark.py", line 28, in <module>
>     imgs = io.imread(os.path.join(FilePath,name))
>   File "E:\Anaconda3\envs\DFD\lib\site-packages\skimage\io\_io.py", line 48, in imread
>     img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
>   File "E:\Anaconda3\envs\DFD\lib\site-packages\skimage\io\manage_plugins.py", line 209, in call_plugin
>     return func(*args, **kwargs)
>   File "E:\Anaconda3\envs\DFD\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 10, in imread
>     return np.asarray(imageio_imread(*args, **kwargs))
>   File "E:\Anaconda3\envs\DFD\lib\site-packages\imageio\core\functions.py", line 265, in imread
>     reader = read(uri, format, "i", **kwargs)
>   File "E:\Anaconda3\envs\DFD\lib\site-packages\imageio\core\functions.py", line 182, in get_reader
>     "Could not find a format to read the specified file in %s mode" % modename
> ValueError: Could not find a format to read the specified file in single-image mode
> ```
> 
> How can I get past this error?
> Thanks in advance

Hi, I did not meet this problem before. If possible, you can send these two images to me (csxmli@hit.edu.cn), and I will check what happened.

**Comment by csxmli2016** [comment]
> Hi,
> I am trying to run `python get_face_landmark.py` with 2 test images n000024_0042_02 and n000056_0060_01
> but it returned with:
> 
> ```
> (DFD) G:\DFDNet\DFDNet\FaceLandmarkDetection>python get_face_landmark.py
> (0, 'Landmarks')
> Traceback (most recent call last):
>   File "get_face_landmark.py", line 28, in <module>
>     imgs = io.imread(os.path.join(FilePath,name))
>   File "E:\Anaconda3\envs\DFD\lib\site-packages\skimage\io\_io.py", line 48, in imread
>     img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
>   File "E:\Anaconda3\envs\DFD\lib\site-packages\skimage\io\manage_plugins.py", line 209, in call_plugin
>     return func(*args, **kwargs)
>   File "E:\Anaconda3\envs\DFD\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 10, in imread
>     return np.asarray(imageio_imread(*args, **kwargs))
>   File "E:\Anaconda3\envs\DFD\lib\site-packages\imageio\core\functions.py", line 265, in imread
>     reader = read(uri, format, "i", **kwargs)
>   File "E:\Anaconda3\envs\DFD\lib\site-packages\imageio\core\functions.py", line 182, in get_reader
>     "Could not find a format to read the specified file in %s mode" % modename
> ValueError: Could not find a format to read the specified file in single-image mode
> ```
> 
> How can I get past this error?
> Thanks in advance

Hi, this is caused by the wrong url path. Please make sure that the [file path](https://github.com/csxmli2016/DFDNet/blob/94d55951961bbdc7cb72d460ab9bda545cb72029/FaceLandmarkDetection/get_face_landmark.py#L17) only these two images (without the landmarks file in the same folder). 
If you just want to test with the provided test images in './TestData/RealVgg/Imgs', you can directly run step 3 without steps 1 and 2.

**Comment by cloudweather** [comment]
It worked after I changed the landmarks file location to ./TestData/RealVgg/Landmarks/
