### ISSUE TITLE
About training 

### ISSUE THREAD

**Issue by xjw00654** [csxmli2016/DFDNet#43]
I have tried to use official pix2pixHD repo as the template to reproduce your code on 2080Ti but found OOM ERROR.

Noticed that you used Tesla V100, so i am questioning about how much memory will costed (on 512x512) when training when i use --fp16 or not use --fp16 respectively？

**Comment by csxmli2016** [comment]
> I have tried to use official pix2pixHD repo as the template to reproduce your code on 2080Ti but found OOM ERROR.
> 
> Noticed that you used Tesla V100, so i am questioning about how much memory will costed (on 512x512) when training when i use --fp16 or not use --fp16 respectively？

Hi, the Tesla V100 server that I used was released. You can use a LightCNN to replace Vgg and only use scale-1 and 2 features. This can reduce the memory and achieve comparable performance.
