### ISSUE TITLE
Possibility to skip the face detection stage?

### ISSUE THREAD

**Issue by ivellios1988** [csxmli2016/DFDNet#44]
Just out of curiosity, is it possible to skip the face detection stage when running DFDNet? Would it crash or just keep working? I love experimenting and I'm curious how the result would look like since I'm looking for a tool that would help me enhance hair in photos where subjects have long hairs. So far I tested a lot of solutions such as DFDNet, Remini, and other apps and scripts of this type and they only enhance hairs around faces, leaving the rest of the hair looking like the subject put a load of glue on their head

**Comment by csxmli2016** [comment]
> Just out of curiosity, is it possible to skip the face detection stage when running DFDNet? Would it crash or just keep working? I love experimenting and I'm curious how the result would look like since I'm looking for a tool that would help me enhance hair in photos where subjects have long hairs. So far I tested a lot of solutions such as DFDNet, Remini, and other apps and scripts of this type and they only enhance hairs around faces, leaving the rest of the hair looking like the subject put a load of glue on their head

Hi, DFDNet is proposed to handle face regions. So it is a must to detect face. As for hair, I think you can extract them, and use irregular region fair discriminator or style constrains to enhance them.
