### ISSUE TITLE
Batch Size must be 'batchSize'

### ISSUE THREAD

**Issue by zarc70** [csxmli2016/DFDNet#45]
Hi,

I noticed while trying to change the batch size that the only way the option can be parsed is by writing batchSize, capitalizing Size, but not batch. I don't know if this is fixable, but thought it might be good to put in a details section if not.

**Comment by csxmli2016** [comment]
> Hi,
> 
> I noticed while trying to change the batch size that the only way the option can be parsed is by writing batchSize, capitalizing Size, but not batch. I don't know if this is fixable, but thought it might be good to put in a details section if not.

Hi, other parameters, like batchsize, should not be changed in test phase. In current settings, one gpu can only handle one image.
