### ISSUE TITLE
set of examples of enhanced videos? 

### ISSUE THREAD

**Issue by alessiapacca** [csxmli2016/DFDNet#46]
hey! I am enhancing my own videos but it takes a long time.
Is there a chance you have a folder with some examples of enhanced videos/frames sequences? 
Thanks!

**Comment by alessiapacca** [comment]
@csxmli2016 @AutomatykaJava

**Comment by csxmli2016** [comment]
> hey! I am enhancing my own videos but it takes a long time.
> Is there a chance you have a folder with some examples of enhanced videos/frames sequences?
> Thanks!

Hi，you can refer to here 
https://drive.google.com/file/d/1IXA9CublUsAyKPB_LGay0-cZk2IfDKJf/view?usp=sharing
to find the enhanced videos.
