### ISSUE TITLE
How to let crop and landmark detection run on gpu while running restoration on cpu

### ISSUE THREAD

**Issue by Michaelwhite34** [csxmli2016/DFDNet#47]
I have the question because my gpu doesn't have enough memory.

**Comment by Michaelwhite34** [comment]
Another question,is it possible to set some parameters manually ? For some highly compressed videos,there will be some kind of noise in the face (which can't be eliminated by denoise method),DFDNet will take it as face feature and produce some kind of 
freckle in the face.So can we manually set the face to be smooth (without much 
speckle )？

**Comment by csxmli2016** [comment]
> I have the question because my gpu doesn't have enough memory.

Hi, you can run the first two steps with gpu. Then with the detected and cropped results saved in the filepath, you can comment the two steps and directly run the restoration process with cpu.

**Comment by csxmli2016** [comment]
> Another question,is it possible to set some parameters manually ? For some highly compressed videos,there will be some kind of noise in the face (which can't be eliminated by denoise method),DFDNet will take it as face feature and produce some kind of
> freckle in the face.So can we manually set the face to be smooth (without much
> speckle )？

Good suggestion. Maybe it is better to consider this degradation in conducting training pairs.
