### ISSUE TITLE
did anybody succeed in making it working on gpu without CUDA out of memory error? 

### ISSUE THREAD

**Issue by alessiapacca** [csxmli2016/DFDNet#49]
I was never able to run the test on a GPU, using a 2070 gpu.
I was wondering if anybody was able to find where the problem is with the allocation of memory: I thought it was the number of test images, or the dictionary, but I used my own small dictionary and just 10 images, and it still gives me a cuda out of memory error.

**Comment by csxmli2016** [comment]
> I was never able to run the test on a GPU, using a 2070 gpu.
> I was wondering if anybody was able to find where the problem is with the allocation of memory: I thought it was the number of test images, or the dictionary, but I used my own small dictionary and just 10 images, and it still gives me a cuda out of memory error.

Hi, only 8GB memory in 2070 is not enough to run this code on GPU mode. You can use 1080Ti or 2080 Ti (at least 12 GB).
