### ISSUE TITLE
any good ways to not get CUDA out of memory?

### ISSUE THREAD

**Issue by cloudweather** [csxmli2016/DFDNet#5]
fyi
The image size is 512x512, my GPU is GTX1080 with 8GB VRAM

**Comment by csxmli2016** [comment]
> fyi
> The image size is 512x512, my GPU is GTX1080 with 8GB VRAM

Hi, you can simply use cpu by setting ``` opt.gpu_ids = []``` in [here](https://github.com/csxmli2016/DFDNet/blob/94d55951961bbdc7cb72d460ab9bda545cb72029/test_FaceDict.py#L100). It runs successfully in my computer.

**Comment by cloudweather** [comment]
ok thanks, running it on CPU works.
