### ISSUE TITLE
How to get a pretrained VGGFace2 model??

### ISSUE THREAD

**Issue by SongDoHou** [csxmli2016/DFDNet#50]
Hi, How can I get a VGG-19 model file which is pretrained VGG-Face2 dataset??

Because I want to try construct dictionaries but I can find only VGG-16 model on the VGGFace2 website.

**Comment by csxmli2016** [comment]
> Hi, How can I get a VGG-19 model file which is pretrained VGG-Face2 dataset??
> 
> Because I want to try construct dictionaries but I can find only VGG-16 model on the VGGFace2 website.

Hi, you can train it by yourself with the VggFace2 datasets.
