### ISSUE TITLE
About provided component dictionaries and VGG 19 weights file

### ISSUE THREAD

**Issue by SongDoHou** [csxmli2016/DFDNet#51]
Hi.

I want you ask about component dictionaries and vgg 19 weights file that you provided. 

which resolution of images are used for training?? is it 256 x 256 or 512 x 512 ??

In the paper, for handling 256 x 256 images, left/right eyes, nose and mouth on scale-1 are set to 40/40, 25, 55 respectively.  So I think 256 x 256 resolution images are used for training. 
But the provided model is making 512 x 512 resolution image. 
I'm just wondering about that. 
Thank you in advance :)

**Comment by csxmli2016** [comment]
> Hi.
> 
> I want you ask about component dictionaries and vgg 19 weights file that you provided.
> 
> which resolution of images are used for training?? is it 256 x 256 or 512 x 512 ??
> 
> In the paper, for handling 256 x 256 images, left/right eyes, nose and mouth on scale-1 are set to 40/40, 25, 55 respectively. So I think 256 x 256 resolution images are used for training.
> But the provided model is making 512 x 512 resolution image.
> I'm just wondering about that.
> Thank you in advance :)

We trained two models, i.e., 256 and 512. The 512 model has more application values, so we only release this one.

**Comment by SongDoHou** [comment]
Thanks. 

So it means that component dictionaries are made with 512 x 512 resolution images??

**Comment by csxmli2016** [comment]
> Thanks.
> 
> So it means that component dictionaries are made with 512 x 512 resolution images??

Obviously, 256 model conducted the dictionary on 256 images, 512 model on 512 images.

**Comment by SongDoHou** [comment]
Thank you for the information.
Could you provide pretrained model for 256 x 256 resolution ??

**Comment by csxmli2016** [comment]
> Thank you for the information.
> Could you provide pretrained model for 256 x 256 resolution ??

Hi, we just release the 512 model to show its effectiveness on visual performance and did not plan to release others.
