### ISSUE TITLE
Step 4 Error

### ISSUE THREAD

**Issue by chrisume** [csxmli2016/DFDNet#9]
In most cases I get an error while merging back to the original frame.
I can see the enhanced face in the : step3_restorecropface  folder.

Sometimes it works, but in most cases I just get this error.

###############################################################################
###############################################################################

Final Restoring 04377.png
Traceback (most recent call last):
  File "test_FaceDict.py", line 270, in <module>
    reverse_align(WholeInputPath, FaceResultPath, ParamPath, SaveWholePath, UpScaleWhole)
  File "test_FaceDict.py", line 59, in reverse_align
    input_img = dlib.load_rgb_image(input_path)
RuntimeError: Unable to open file: /home/dfl2/Desktop/DFDNet-whole/TestData/TestWhole/04377.png

**Comment by Lubsey1** [comment]
I'm getting a very similair error at the same stage
`Final Restoring /content/DFDNet/Images/frames/enhanced/Step3_RestoreCropFace
Traceback (most recent call last):
  File "/content/DFDNet/test_FaceDict_whole.py", line 270, in <module>
    reverse_align(WholeInputPath, FaceResultPath, ParamPath, SaveWholePath, UpScaleWhole)
  File "/content/DFDNet/test_FaceDict_whole.py", line 59, in reverse_align
    input_img = dlib.load_rgb_image(input_path)
RuntimeError: Unknown image file format: Unable to load image in file /content/DFDNet/Images/frames/enhanced/Step3_RestoreCropFace`

**Comment by csxmli2016** [comment]
> In most cases I get an error while merging back to the original frame.
> I can see the enhanced face in the : step3_restorecropface folder.
> 
> Sometimes it works, but in most cases I just get this error.
> 
> ###############################################################################
> ############### Step 4: Paste the Restored Face to the Input Image ############
> ###############################################################################
> 
> Final Restoring 04377.png
> Traceback (most recent call last):
> File "test_FaceDict.py", line 270, in
> reverse_align(WholeInputPath, FaceResultPath, ParamPath, SaveWholePath, UpScaleWhole)
> File "test_FaceDict.py", line 59, in reverse_align
> input_img = dlib.load_rgb_image(input_path)
> RuntimeError: Unable to open file: /home/dfl2/Desktop/DFDNet-whole/TestData/TestWhole/04377.png

I am not sure about the given information. It seems that this image 04377.png is not in the target folder. Can you check this folder and debug it to find what happened? Maybe there is something that I ignored. Please give me more information about it. I have also updated a new version to fix some bugs.

**Comment by chrisume** [comment]
I haven't been able to reproduce this error.

Its probably due to having images with higher dimensions in the cropped folder.
