### ISSUE TITLE
weird results, what's wrong?

### ISSUE THREAD

**Issue by hungtooc** [csxmli2016/DFDNet#98]
Step3_RestoreCropFace
![f1d5071e-59f9-415e-b0a2-f1919992ef64](https://user-images.githubusercontent.com/24487114/132973572-1562885e-04bb-4973-9655-e620cc9e68d4.jpeg)
Step4_FinalResults
![4445fe71-db99-427d-8ff7-5a4f2a31cc14](https://user-images.githubusercontent.com/24487114/132973553-4d88ffd2-93cb-451d-85f8-7610552c14eb.jpeg)

**Comment by cliobeach** [comment]
I HAVE THE SOME problem

**Comment by hungtooc** [comment]
> I HAVE THE SOME problem

yes. Folow this colab will have no issue: https://colab.research.google.com/github/hopperrr/DFDNet_Colab/blob/master/DFDNet_Blind_Face_Restoration.ipynb

**Comment by hungtooc** [comment]
> > I HAVE THE SOME problem
> 
> yes. Folow this colab will have no issue: https://colab.research.google.com/github/hopperrr/DFDNet_Colab/blob/master/DFDNet_Blind_Face_Restoration.ipynb
